<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title><?=get_settings_value('system_name')?> | Authenticate</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
    <link rel="stylesheet" href="<?=base_url('assets/admin/plugins/fontawesome-free/css/all.min.css')?>">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="<?=base_url('assets/admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css')?>">
    <!-- Theme style -->
    <link rel="stylesheet" href="<?=base_url('assets/admin/dist/css/adminlte.css')?>">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
	<!-- Custom style -->
    <link rel="stylesheet" href="<?=base_url('assets/admin/css/my_theme.css')?>">
</head>
<body class="">

<div class="login">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="login-inner-form">
                        <div class="details">
                            <a href="<?=base_url()?>">
                                <?php 
									$image = get_settings_value('logo');
									if (!empty($image)) {
										$sys_img = base_url('assets/uploads/system_images/' . $image);
									} else {
										$sys_img = base_url('assets/admin/dist/img/logo-default.png');
									} 
								?>
                                <img src="<?=$sys_img?>" alt="logo" class="img-fluid">
                            </a>
                            <h3><?=$details->email;?></h3>
							<?php
							if($this->session->flashdata('error_msg')!=''){
							?>
							<div class="alert alert-danger alert-dismissible">
							  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
							  <h5><i class="icon fas fa-ban"></i><?php echo $this->session->flashdata('error_msg'); ?>!!</h5>                  
							</div>
							<?php
							}
							?>
                            <form action="" method="post" autocomplete="off">
                                <div class="form-group">
                                    <input type="number" class="form-control <?=($this->session->flashdata('error_msg')!='')?'is-invalid':'';?>" placeholder="<?=($this->session->flashdata('error_msg')!='')?$this->session->flashdata('error_msg'):'Enter Google Authenticator Code';?>" name="code" required autocomplete="off">
                                </div>
                                <div class="form-group">
                                    
                                </div>
                                <div class="checkbox clearfix">
                                    <label class="form-check-label text-warning" for="rememberMe">
                                            Enter the verification code generated by Google Authenticator app on your phone.
									</label>
                                </div>
                                <div class="form-group mb-0">
                                    <button type="submit" class="btn-md btn-theme btn-block">Login</button>
                                </div>
                            </form>
							
                            <div class="social-auth-links text-center mb-3 row">
								<p class="text-center col-12">Get Google Authenticator on your phone</p>
								<a  class="col-6 "href="https://itunes.apple.com/us/app/google-authenticator/id388497605?mt=8" target="_blank">
									<img class="col-12 " src="<?=base_url('assets/admin/images/iphone.png')?>" />
								</a>
								<a  class="col-6 "href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en" target="_blank">
									<img class="col-12 " src="<?=base_url('assets/admin/images/android.png')?>" />
								</a>								
							</div>
                        </div>
                        <div class="footer">
                            <span><a href="<?=base_url('Auth/logout')?>">Or sign in as a different user</a></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




<!-- jQuery -->
<script src="<?=base_url('assets/admin/plugins/jquery/jquery.min.js')?>"></script>
<!-- Bootstrap 4 -->
<script src="<?=base_url('assets/admin/plugins/bootstrap/js/bootstrap.bundle.min.js')?>"></script>

</body>
</html>
